#  <span style='color:#43b8f7'>Technical Test</span>
 <img src="https://upload.wikimedia.org/wikipedia/commons/thumb/c/cc/BlaBlaCar_logo.svg/1024px-BlaBlaCar_logo.svg.png"
     alt="Markdown Monster icon"
     style="float: left; margin-right: 10px;width:25%;height:50%" />

## I -Define functions

In [458]:
# the paths of the files containig input
path1 = "blabla.txt"
path2 = "blabla_2.txt"

In [459]:
def read_file(path):

    # Return the mowers in the input file & the max size of lawn 
    
    file1 = open(path, 'r') 
    count = 0
    mowers = []
    line = file1.readline()
    
    #add the law size to the list
    mowers.append(line.strip())
    
    # append the mowers to ower list
    while True: 
        count += 1
        mower = {}
        # Get next line from file 
        line = file1.readline() 
        
        # if line is empty 
        # end of file is reached 
        if not line: 
            break
#         print("Line{}: {}".format(count, line.strip())) 
        #### form the mowers object
        line_nav = file1.readline()
        mower["x"]= int(line.strip().split(sep=" ")[0])
        mower["y"]= int(line.strip().split(sep=" ")[1])
        mower["d"]= line.strip().split(sep=" ")[2]
        mower["nav"] = line_nav.strip()+'0'
        mower["id"] = count
        # add mower to the list
        mowers.append(mower)
    print(mowers)
    return mowers
    file1.close()

In [460]:
def left(d):
    # return the next left direction based on actual direction
    
    print('L')
    if d== 'N' : d='W'
    elif d == 'W' : d='S'
    elif d== 'S' : d='E'
    else : d='N'
    return d
    

In [461]:
def right(d):
    # turn right based on the actual direction(Nord, South)
    
    print('R')
    if d== 'N' : d='E'
    elif d == 'W' : d='N'
    elif d== 'S' : d='W'
    else : d='S'
    return d

In [462]:
def forward(x,y,d,x_max,y_max):
    # returns the next position in the lawn after a forward instruction
    
    print('F')
    if d== 'N' : 
        if y<y_max-1 :y+=1
    elif d == 'W' : 
        if x>0 : x-=1
    elif d== 'S' : 
        if y>0 : y-=1
    else :
        if x< x_max-1 : x+=1
    return x,y

In [463]:
def move(mower,lawn_matrix) : 
# """   
#     move the mower with x0,y0,Direction and navigation path inside the lawn matrix
# """
    finish = 0
    # get next instruction
    inst = mower["nav"][0]
    if inst == 'L': 
        mower['d'] = left(mower['d'])
        mower['nav'] = mower['nav'][1:]
        print('the mower N° :',mower['id'])
    elif inst == 'R' :
        mower['d'] = right(mower['d'])
        mower['nav'] = mower['nav'][1:]
        print('the mower N° :',mower['id'])
    elif inst == "0":
        finish = 1
    else :
        x,y =  forward(mower['x'],mower['y'],mower['d'],lawn_matrix.shape[0],lawn_matrix.shape[1])
        mower['nav'] = mower['nav'][1:]
        #check if the next position is available to move if not stay
        if lawn_matrix[x,y]==0 : 
            lawn_matrix[x,y]= lawn_matrix[mower['x'],mower['y']]
            lawn_matrix[mower['x'],mower['y']] = 0
            mower['x']=x
            mower['y']=y
        print('the mower N° :',mower['id'])
    return mower, lawn_matrix,finish

## II- Execution :
### 1- Prepare the variables 
### <span style='color:red'>if you get an error in the next cell :</span>  ValueError: invalid literal for int() with base 10

Please go to the blabla.txt file and delete the result :  
**Result**  
**1 3 N**  
**5 1 E**  


In [464]:
# get the contents of the input file 
mowers = read_file(path1)

['5 5', {'x': 1, 'y': 2, 'd': 'N', 'nav': 'LFLFLFLFF0', 'id': 1}, {'x': 3, 'y': 3, 'd': 'E', 'nav': 'FFRFFRFRRF0', 'id': 2}]


In [465]:
# take  a look ;) at our mawers 
mowers

['5 5',
 {'x': 1, 'y': 2, 'd': 'N', 'nav': 'LFLFLFLFF0', 'id': 1},
 {'x': 3, 'y': 3, 'd': 'E', 'nav': 'FFRFFRFRRF0', 'id': 2}]

In [466]:
lawn_size = mowers[0]
mowers_in_move = mowers[1:]
result =[]


In [467]:
# the lawn is modelized with a numpy matrix, the position of mowers contain their ids && the rest is zeros
import numpy as np
lawn_size.split(" ")
lawn_matrix = np.zeros(
    (int(lawn_size.split(" ")[0])+1,
     int(lawn_size.split(" ")[1])+1
    ))

# puting mowers in their initail positions
for i in range(len(mowers_in_move)) :
    lawn_matrix[int(mowers_in_move[i]['x']),int(mowers_in_move[i]['y'])] = mowers_in_move[i]['id']

In [468]:

print("Shape lawn ",lawn_matrix.shape)
print("Mowers in move :",mowers_in_move)
print("Result :",result)
print("The lawn matrix :")
print(lawn_matrix)

Shape lawn  (6, 6)
Mowers in move : [{'x': 1, 'y': 2, 'd': 'N', 'nav': 'LFLFLFLFF0', 'id': 1}, {'x': 3, 'y': 3, 'd': 'E', 'nav': 'FFRFFRFRRF0', 'id': 2}]
Result : []
The lawn matrix :
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 2. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


### 2- Let's mow the lawn

In [469]:
while len(mowers_in_move) > 0 :
#     finish = 0
    to_del=[]
    for i in range(len(mowers_in_move)) :
        print(mowers_in_move)
        print(lawn_matrix)
        mowers_in_move[i], lawn_matrix,finish = move(mowers_in_move[i],lawn_matrix)
        if finish == 1 : 
            #  mower is at last position it will be poped from mawers_in_move 
            to_del.append(i)
#             mowers_in_move.pop(i)
    #delete mowers at finish and append its last sitauation to the result
    for j in range(len(to_del)):
        result.append(mowers_in_move[to_del[j]])
        mowers_in_move[to_del[j]]= -1
    for j in range(len(to_del)):
#         delete the items =-1 from the list wich is equivalent to mowers at finish
        mowers_in_move.remove(-1)

#         del(mowers_in_move[to_del[j]])
#         mowers_in_move.pop(to_del[j])



[{'x': 1, 'y': 2, 'd': 'N', 'nav': 'LFLFLFLFF0', 'id': 1}, {'x': 3, 'y': 3, 'd': 'E', 'nav': 'FFRFFRFRRF0', 'id': 2}]
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 2. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
L
the mower N° : 1
[{'x': 1, 'y': 2, 'd': 'W', 'nav': 'FLFLFLFF0', 'id': 1}, {'x': 3, 'y': 3, 'd': 'E', 'nav': 'FFRFFRFRRF0', 'id': 2}]
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 2. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
F
the mower N° : 2
[{'x': 1, 'y': 2, 'd': 'W', 'nav': 'FLFLFLFF0', 'id': 1}, {'x': 4, 'y': 3, 'd': 'E', 'nav': 'FRFFRFRRF0', 'id': 2}]
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 2. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
F
the mower N° : 1
[{'x': 0, 'y': 2, 'd': 'W', 'nav': 'LFLFLFF0', 'id': 1}, {'x': 4, 'y': 3, 'd': 'E', 'nav': 'FRFFRFRRF0', 'id': 2}]
[[0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 2

In [470]:
result

[{'x': 1, 'y': 3, 'd': 'N', 'nav': '0', 'id': 1},
 {'x': 5, 'y': 1, 'd': 'E', 'nav': '0', 'id': 2}]

##   <span style="color:red"> Warning !!!</span> ;)
the (0,0) of the matrix is at **Left Top** corner



In [471]:
print("This is the result in the matrix : ")
lawn_matrix

This is the result in the matrix : 


array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 2., 0., 0., 0., 0.]])

## Write the Result to the file 

In [472]:
result_to_write = [0]*len(result)
for m in result :
    result_to_write[m['id']-1] = m

In [473]:
# Open a file with access mode 'a'
file_object = open(path1, 'a')
# skip line and append 'Result'
file_object.write('\r\n')
file_object.write('Result')
for mower in result_to_write :
    file_object.write('\r')
    file_object.write("{} {} {}".format(mower['x'],mower['y'] , mower['d']))
    
file_object.close()